<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 7.2.2 (Python 3.12.2 on win32)" generated="2025-05-17T16:35:22.684713" rpa="false" schemaversion="5">
<suite id="s1" name="TC03" source="C:\Users\asus\PycharmProjects\UdemyRobot\tESTS\TC03.robot">
<test id="s1-t1" name="Login test with ${username} and ${password}" line="7">
<status status="FAIL" start="2025-05-17T16:35:23.237713" elapsed="0.002044">Test cannot be empty.</status>
</test>
<status status="FAIL" start="2025-05-17T16:35:22.687715" elapsed="0.553030"/>
</suite>
<statistics>
<total>
<stat pass="0" fail="1" skip="0">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat name="TC03" id="s1" pass="0" fail="1" skip="0">TC03</stat>
</suite>
</statistics>
<errors>
<msg time="2025-05-17T16:35:23.231712" level="ERROR">[ DataDriver ] Error in robot file:
  File "C:\Users\asus\PycharmProjects\UdemyRobot\tESTS\TC03.robot", line 0</msg>
<msg time="2025-05-17T16:35:23.231712" level="ERROR">In source file:
  File "Resource/data.csv", line 0</msg>
<msg time="2025-05-17T16:35:23.235714" level="ERROR">Calling method '_start_suite' of listener 'DataDriver' failed: ValueError: Unassigned requiered argument detected: ${username}.</msg>
</errors>
</robot>
